:ems:
  :ems_ibm_cloud_virtual_servers:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
        :power:
          :critical:
            - IBM_CLOUD_VIRTUAL_SERVERS_instance_power_on
            - IBM_CLOUD_VIRTUAL_SERVERS_instance_power_off
:http_proxy:
  :ibm_cloud_virtual_servers:
    :host:
    :password:
    :port:
    :user:
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_ibm_cloud_virtual_servers:
        :poll: 20.seconds
    :queue_worker_base:
      :ems_metrics_collector_worker:
        :ems_metrics_collector_worker_ibm_cloud_virtual_servers: {}
      :ems_refresh_worker:
        :ems_refresh_worker_ibm_cloud_virtual_servers: {}
